### ISSUE TITLE
Stereotype for transport network is missing

### ISSUE THREAD

**Issue by Krueger-AlbrechtConsult** [FRAME-NEXT/FRAME#11]
![grafik](https://user-images.githubusercontent.com/74711590/101161609-5dcdd500-3631-11eb-97d2-1dd6caba495f.png)
This is Part of the domain template in wiki.
http://wikiits.albrechtconsult.com/index.php?title=NAP_Overall_concepts

**Comment by AustriaTech** [comment]
Could the ITS Domain modelled as Tagged Value of the ITS Service?
... or is a complete new Stereotype needed?

**Comment by willibecker** [comment]
We use the motivational layer to give a good overview of the context of the service. One important information for that is the targeted transport network. In order to expose this information, we propose a very simple stereotype from Archimate::Location. A connector to the service description could be helpful to connect the transport network to the service.
