### ISSUE TITLE
Change FRAME Repository navigation cell name to FRAME Functional View

### ISSUE THREAD

**Issue by mertaksac** [FRAME-NEXT/FRAME#17]
![image](https://user-images.githubusercontent.com/71774192/102392239-de081900-3fe7-11eb-96f4-8af9d88778cf.png)

The navigation cell FRAME Repository in the landing page is (or should be) linked to the "Context Diagram - System" diagram under the Frame Functional View package.

This navigation cell should be used to "browse" the functional view of FRAME.

FRAME Repository do not consist of only the Functional View, we also have the FRAME User Needs under the FRAME Repository package.

Therefore renaming this cell as "FRAME Functional View" would better suit our purposes.

**Comment by AustriaTech** [comment]
To link the Userneed link and the FRAME repositoy I propose a diffrent idea:
Whats about a landing page for the FRAME Functional View and the FRAME Userneeds including a short introduction?

**Comment by mertaksac** [comment]
This issue was discussed in the Maintainer's Telco on 21st of January 2021.

It was decided to include a separate "landing page" (diagram) for the FRAME Repository that would include navigation cells for the User Needs and the context diagram (Functional view).

This was executed in the V4.43 of the FRAME Architecture Tool.

**Comment by mertaksac** [comment]
Before Closing this issue I would like to make one more suggestion:

Now we have 2 navigation cells for separate parts of the FRAME Repository.
![image](https://user-images.githubusercontent.com/71774192/105831741-25ff6000-5fd8-11eb-8902-8ed335835060.png)

One goes to a diagram where all User Needs can be found and the other one goes to a diagram where the user can browse the entirety of the functions that exist in FRAME Repository.

Shouldn't we name the navigation cells as FRAME User Needs and FRAME Functional View, respectively?

or would that be a wrong assumption since the "Context Diagram" do not have terminators in it (so that it is not the full "functional view")?

**Comment by burespe1** [comment]
thanks for the suggestion.

I like the "FRAME User Needs" and "FRAME Functional View"
I am however content with both options, so I do not have really strong
opposition to current names.

Petr Bureš
email: burespe1@gmail.com
mob.: (+420) 777 131 603


út 26. 1. 2021 v 11:21 odesílatel Mert <notifications@github.com> napsal:

**Comment by AustriaTech** [comment]
Dear Mert,

 

Thank you for your e-mails about the new landing page for the FRAME Repository.  I would like pick up on the points you have raised.

 

1.      Personally I found the User Needs diagram too large and hence not very easy to study.  If we are going to persist with using it then I think the layout needs to be improved.  An alternative to the existing diagram is to have diagrams at different levels, as in the Functional View.  This can be implemented by having a top-level diagram showing all the User Need Groups, then a diagram for each Group showing the Topics, then a diagram for each Topic showing the Services and then a diagram for each Service showing its User Needs.  Users would be able to move down the hierarchy by clicking on the Group, Topic or Service in each diagram.  For those Groups that have a small number of Topics, Services or User Needs, some of these diagram levels could be missed out making the Group easier to navigate.

2.      On my computer the User Needs diagram does take a few seconds to open.  Doing what I have suggested above, would I think solve this problem because there would only be a smaller number of elements to load at any one time.  The time and difficulty for Users to work their way down through the hierarchy of User Needs diagrams would in my view be not much different from having to scroll down/across the existing diagram.  It would also be possible to create a sensible print of each diagram if that was required.

3.      Turning to the Functional View and the Context Diagram, I found that the Diagram does not actually give access to the functionality, at least not directly.  You have to know that to get this access you have to open the “Properties” window for the “System”, select the “Links” window, right click on the Functional Area of interest and select “Locate Related Element”, which will open up the “Functionality” package in the Project Browser to show the DFD and Functional Tree for the selected Functional Area.  How much knowledge of EA are we going to assume that Users have?  Should we include some instructions about what to do?  I have suggested below the text I have in mind, which would appear as soon as you open the “Properties” window for the “System”.

 

This represents the highest level of functionality provided in the FRAME Architecture.  The functionality consists of a number of Functional Areas that are linked to the Terminators representing the outside world through the Terminator Data Flows shown in the Context Diagram.

 

To directly access the content of a Functional Area, either open the Project Browser and expand the Functional View package, or open the "Links" window for the “System”, select the Functional Area and "Locate Related Element".  This will open the "Project Browser" and give access to its Data Flow Diagram, Functional Tree Diagram and the package containing its functionality.

 

4.      If you select “Links” in the “Properties” window for the “System” in the Context Diagram, you will find that only a very small number of the Data Flows in DFD0 are listed.  I have tried to add one of the missing ones using the “Add” option available when a Data Flow is selected through the Project Browser, but without success.  Those that do appear have an “Element Stereotype” of “FRAMEITS”, which I cannot find using the “Add” option.  I think it will be confusing for Users if some Data Flows are included in the list available in the “Links” window and others are not but I do not know how to add those that are missing.  

 

Kind regards,

 

Richard 

 

 

Richard Bossom

Mobile Phone: +44 (0)7719196246 (voicemail available)

Skype ID: rapbossom

 

Richard Bossom ITS Consulting Limited.

Registered in England and Wales .  Registered Number: 07684384

Registered Office: Towngate House, 2-8 Parkstone Road , Poole, Dorset .  BH15 7TD

Postal Address: 6 Goldfinch Road, Creekmoor, Poole, Dorset, BH17 7TD, UK

The information contained in this email is confidential and intended solely for the addressee. Any access to this e-mail by anyone else is unauthorized. If you are not one of the intended recipients or have received this e-mail by mistake, please notify the sender immediately and delete this e-mail. Any unauthorized disclosure, copying or distribution of the material contained in this e-mail is strictly forbidden.

**Comment by mertaksac** [comment]
Dear Richard, 

For your 3rd and 4th points, the navigation cell on the FRAME Repository (the one I suggested to be renamed as FRAME Functional View) is taking you to the Context Diagram. After that the pink box written SYSTEM on it should be linked to the DFD0 diagram, (it is much more straight forward process then you have described in your previous comment, and it should already come linked with the version that we will publish on frame-next.eu, so the user actually should not do anything rather than double clicking). 

Upon double clicking on the the pink box (system) it will directly take you to the DFD0. Then you can visit each functional area by again double clicking on them. When you are done investigating a functional are you will be able to go back to DFD0 with the 
![image](https://user-images.githubusercontent.com/71774192/105854106-84880680-5ff7-11eb-83d0-725be5405d47.png) icon on top (where the name of the diagram is written) and again using the same button you must be able to go back all the way to the context diagram. (just as described in the user guide part 2)

I really do not know why this "linkage" is not already done, most probably it was intended but was overlooked in between many changes done in V4.43.

**Comment by mertaksac** [comment]
And regarding points 1 and 2,

I agree with your comments. I have uploaded a modified version of V4.43 (V4.43-MERT) with the changes you have suggested to Austriatech Cloud: here.

Please have a look if this way of organizing the diagrams are better.

**Comment by mertaksac** [comment]
This issue was discussed in Maintainer's telco on 3 February 2020.

It was decided to change "names" of the Navigation Cells as follows:

FRAME User Needs
FRAME Functional view
