### ISSUE TITLE
Do we really need 5 different stereotypes for representing the data flows?

### ISSUE THREAD

**Issue by mertaksac** [FRAME-NEXT/FRAME#20]
At the moment we have 5 different stereotypes of data flows in FRAME Toolbox:

![image](https://user-images.githubusercontent.com/71774192/102699500-5247f400-4256-11eb-8528-dcaf3f540316.png)

Important: these are not coming from the FRAME Repository, the stereotypes on the toolbox are for the "new" elements that the user would be needing to create their own architectures.

The stereotypes that are currently used in the FRAME Repository is coming from the toolboxes that the Sparx have created; namely the "Context Toolbox" and the "DFD Toolbox" inside Frame Next Technology.

![image](https://user-images.githubusercontent.com/71774192/102699752-38a7ac00-4258-11eb-90d1-70d30de7937a.png)

![image](https://user-images.githubusercontent.com/71774192/102700001-6c83d100-425a-11eb-9e2e-a5c2a19f6506.png)

Even though the high level data flows are used to represent the data flow in high level DFDs, they do not group the low level data flows in the same manner that the high level functions group the low level functions, i.e. the data flows are not nested hierarchically, one into another (with the exception of TDF, the highest level data flow represented in the context diagram) . The data flows are still drawn one by one on the diagram even in the higher level DFDs, and they still carry the same mnemonics as the do in the lower level DFDs.

**Do they really need to be different stereotypes?**

The rationale behind this question is to reduce the number of stereotypes offered available to the end user.

It would be more practical and less confusing for the user if we offer only one "Data Flow" stereotype to be used in all occasions, compared to expecting the user to use a "TDFLL" while connecting a function to a terminator and then use a "FDFLL" between two low level functions. And only a very limited number of users will be needing higher level representations of functions / data flows, if they ever would do.

The way we represent the entirety of the FRAME functional view, described above, would also be compatible with one single stereotype of data flow. The stereotype of the dataflows would be the same, but we would differentiate the "level" or "direction" of the data flows from their name (and mnemonics). eg.: "to Driver, From the Operator, fo.tio-travel_information_filter_request, to.tio-travel_information_filters, etc.

**Pros**
one stereotype in the toolbox, less confusion, less mistakes.

**Cons**
to be discussed..

Alternative Metamodel Connections:

![image](https://user-images.githubusercontent.com/71774192/102700750-66452300-4261-11eb-98d0-22443ca62154.png)

Source | Type | Target
-- | -- | --
Terminator | OUT | Data Flow
Data Flow | IN | Terminator
FRAME_LLF | OUT | Data Flow
Data Flow | IN | FRAME_LLF
data store | IN | Data Flow
Data Flow | OUT | data store
FRAME_HLF | OUT | Data Flow
Data Flow | IN | FRAME_HLF
Functional Area | OUT | Data Flow
Data Flow | IN | Functional Area

**Comment by bossomr** [comment]
I think this issue needs to be considered in 2 parts: Functional Data Flows and Terminator Data Flows.

(1) Functional Data Flows: the only different between those that link High-level Functions and those link Low-level Functions is that the former are more likely to have component Functional Data Flows, whereas the latter usually do not.  The only reason for the data flows that link High-level Functions to have components is to simplify the Data Flow Diagrams for High-level Functions..  So if we want to reduce the number of stereotypes, then reduce the Functional Data Flows to one type (stereotype).

(2) Terminator Data Flows: these have three types in order to simplify the diagrams in which they appear: Context Diagram, Highest Level Data Flow Diagram (DFD0), Functional Area and High-level Function Data Flow Diagrams. 
(2.1) Context Diagram: Terminator Data Flows in this Diagram are intended be "simple" because it is a "simple" diagram. They always have component Terminator Data Flows, but if any of these change (added or removed) there is no need to change the Terminator Data Flows in the Context Diagram, making it easier to maintain.
(2.2) DFD0: This is a very complex diagram and again the Terminator Data Flows in this DFD are of a particular format to "simplify" their appearance of the DFD.  They also always have components and if any of them change (added or removed) there is no need to change the Terminator Data Flows in  DFD0, again making it easier to maintain.
(2.3) Functional Area and High-level Function Data Flow Diagrams: these Data Flows need to conform to particular formats to make it easier to understand their purposes, e.g. are they to or from Terminators, and to/from which Terminators.  These may have component Data Flows, but not always.  Again the goal was always to "simplify" the appearance of these Diagrams whilst making them easier to understand.

Conclusions:
(1) Only need one type of Functional Data Flow is needed.  The use of two types (stereotypes) does not appear to serve any useful purpose. 
(2) The 3 types (stereotypes) of Terminator Data Flow do serve a purpose, which is to remind those maintaining the Functional View that they need to use different formats for the names used by each type.

**Comment by AustriaTech** [comment]
The single Functional Dataflow was defined already and is in progress.
For the Terminator Data Flows...
There is the question, would it be enough for the maintainer to have a work description or definition for the naming of data flows?
Or is a object separation needed, with different descriptions.
One Terminator Data Flow would improve the usage of the FRAME Model but may lead to unconventional naming.
For both variants we need a good description anyway.
What do you mean?

**Comment by mertaksac** [comment]
This issue was discussed in Maintainer's telco on 3 February 2020.

The general feeling was that we might not need 5 different stereotypes.

The finalization of the discussion was postponed until C-ITS architecture is completed.

**Comment by mertaksac** [comment]
This issue was revisited in the Maintainer's telco on 11 February 2021.

It was agreed that reducing the number of stereotypes for Data Flows would not have negative implications.

to do's regarding this issue:

- [ ] Delete all extra stereotypes until only one remain, rename the remaining stereotype just "Data Flow"
- [ ] Update toolbox
- [ ] Update Metamodel

**Comment by mertaksac** [comment]
The changes were done on Architecture Tool V4.44. This issue is closed.
