### ISSUE TITLE
User Architecture Template Package Structure

### ISSUE THREAD

**Issue by mertaksac** [FRAME-NEXT/FRAME#21]
Right now we have different package structure for our ready-made architectures and the template package we provide the user for them to create their own subset architectures.

The structure for ready-made architectures:

![image](https://user-images.githubusercontent.com/71774192/106951269-9e84c000-6740-11eb-92c4-c9237ec64256.png)

The structure for User Architecture Template:

![image](https://user-images.githubusercontent.com/71774192/106951318-b0666300-6740-11eb-908e-edb019b34595.png)

If you would kindly think about the structure that we will provide in the V5, we could discuss this on the next telco and finalize before we publish the tool.

**Comment by mertaksac** [comment]
I personally think the Physical View should come before the Organizational View (since the logical step after finalizing the Functional View would be continuing describing the Physical View)

Also the Motivational Layer should come before the User Needs.

A rough proposal would be as follows:

0_ Motivational Layer
01 User Needs
02 Functional View
03 Physical View
04 Communication View
06 Organizational View
1_ Business Layer
2_ Application Layer
3_ Data Layer

**Comment by Drees-BASt** [comment]
There is still the problem that the "Views" and the "Layers" come from two different approaches and as I understand it, we have not made it yet to bring them together to one consistent methodology. (and I do not want to re-open this discussion! we will not solve this issue in this project lifetime)

I think a mixture of both worlds on this structural level is very confusing for the user. This is why there is one possibility with the different "Views" and the "Supplements" where all the rest can be found. Also this is not pretty satisfying as I have to admit but it seems to me as the most reasonable solution.

**Comment by burespe1** [comment]
I support Merts and Holgers take here, summarizing the fix:

- [ ] use the eCall structure most appropriate and backwards compatible) with slight modification proposed by Mert (moving Motivation up)
- [] hiding all not critical and orthogonal packages in the Supplement package. 
- suggestion: rename Motivation to Enterprise View since mixing Layer and View is very confusing especially if/when the Layer is orthogonal to the View, which I feel it is. 

Proposed structure:
- _landing page ... diagram explaining the package content and how it fits together
- Motivational (Layer) = Enterprise View
- User Needs ... Is this the package where other requirements reside?
- Functional View
- Physical View
- Organizational View
- Communication View
- supplements ... with all other so far not aligned stuff (1_ Business Layer, 2_ Application Layer, 3_ Data Layer)

**Comment by mertaksac** [comment]
This issue was discussed in the maintainer's telco on 24.02.2021
It was agreed that the user architecture package should exactly duplicate the structure of the ready-made architectures, and have the necessary diagrams and example objects that would be used in the packages inside.

A new User Architecture Template package was created with the empty packages.
It is expected to have one diagram added in each package.

The structure and the order of the packages is not yet finalized as the ready-made architectures are not finished.

**Comment by mertaksac** [comment]
This issue will be temporarily closed since the ready-made architectures are being waited to be finished first.
